//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatatableCRUD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Solicitud
    {
        public int idSolicitud { get; set; }
        public Nullable<int> idPunto { get; set; }
        public string considerandos { get; set; }
        public string resultandos { get; set; }
        public string acuerdos { get; set; }
        public string adjunto { get; set; }
    
        public virtual Punto Punto { get; set; }
    }
}
