
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
namespace Consilium.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Agenda
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Agenda()
    {

        this.PuntoXAgenda = new HashSet<PuntoXAgenda>();

        this.Sesion = new HashSet<Sesion>();

    }

    [Display(Name = "ID Agenda")]
    public int idAgenda { get; set; }
    [Display(Name = "Fecha")]
    public Nullable<System.DateTime> fecha { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    [Display(Name = "Punto por Agenda")]
    public virtual ICollection<PuntoXAgenda> PuntoXAgenda { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    [Display(Name = "Sesión")]
    public virtual ICollection<Sesion> Sesion { get; set; }

}

}
