
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Consilium.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Comision
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Comision()
    {

        this.MiembroXComision = new HashSet<MiembroXComision>();

    }


    public int idComision { get; set; }

    public string nombre { get; set; }

    public string objetivo { get; set; }

    public System.DateTime fechaFin { get; set; }

    public Nullable<System.DateTime> fechaIni { get; set; }

    public string idSesion { get; set; }

    public int idPunto { get; set; }



    public virtual Sesion Sesion { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<MiembroXComision> MiembroXComision { get; set; }

    public virtual Punto Punto { get; set; }

}

}
