//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


using System.ComponentModel.DataAnnotations;
namespace Consilium.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComisionXSesion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ComisionXSesion()
        {
            this.MiembroXComision = new HashSet<MiembroXComision>();
        }
    
        public int idComisionXSesion { get; set; }

        [Display(Name = "ID Comisión")]

        public Nullable<int> idComision { get; set; }
        [Display(Name = "ID Sesión")]
        public Nullable<int> idSesion { get; set; }
        [Display(Name = "Comisión")]
        public virtual Comision Comision { get; set; }
        [Display(Name = "Sesión")]
        public virtual Sesion Sesion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [Display(Name = "Miembros por Comisión")]
        public virtual ICollection<MiembroXComision> MiembroXComision { get; set; }
    }
}
