//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;
namespace Consilium.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EstadoPunto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EstadoPunto()
        {
            this.Punto = new HashSet<Punto>();
        }

        [Display(Name = "ID Estado")]
        public int idEstado { get; set; }
        [Display(Name = "Nombre")]
        public string nombre { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [Display(Name = "Punto")]
        public virtual ICollection<Punto> Punto { get; set; }
    }
}
