
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Consilium.Models
{

using System;
    
public partial class getPuntosSesion_Result1
{

    public string titulo { get; set; }

    public string acuerdos { get; set; }

    public string considerandos { get; set; }

    public string idUsuario { get; set; }

    public string resultandos { get; set; }

    public System.DateTime fecha { get; set; }

}

}
