
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
namespace Consilium.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Justificacion
{
    [Display(Name = "ID Justificación")]
    public int idJustificacion { get; set; }

        [Display(Name = "Fecha")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Fecha requerida")]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> fecha { get; set; }

        [Display(Name = "ID Usuario")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Usuario requerida")]
        public string idUsuario { get; set; }

        [Display(Name = "Asunto")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Asunto requerida")]
        public string asunto { get; set; }

        [Display(Name = "Texto")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Texto requerida")]
        public string texto { get; set; }
        [Display(Name = "Estado")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Estado requerida")]
        public string estado { get; set; }


        [Display(Name = "Usuario")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Usuario requerida")]
        public virtual Usuario Usuario { get; set; }

}

}
