//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


using System.ComponentModel.DataAnnotations;

namespace Consilium.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Logueo
    {
        [Display(Name = "ID Usuario")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Debe de ingresar el ID de usuario")]
        public string idUsuario { get; set; }
        [Display(Name = "Nombre de Usuario")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Nombre de usuario requerido")]
        public string nombreUsuario { get; set; }

        [Display(Name = "Contraseña")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Ingrese su contraseña")]
        public string contrasenna { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
