
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Consilium.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Member
{

    public string Identification { get; set; }

    public string Name { get; set; }

    public string Lastname { get; set; }

    public byte[] Phone { get; set; }

    public string Email { get; set; }

    public string Type { get; set; }

}

}
