//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Consilium.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class MiembroXComision
    {
        [Display(Name = "ID Miembro por comisión")]
        public int idMiembroXComision { get; set; }
        [Display(Name = "ID Usuario")]
        public string idUsuario { get; set; }
        [Display(Name = "ID Comisión por Sesión")]
        public int idComisionXSesion { get; set; }
        [Display(Name = "Tipo Miembro")]
        public string tipoMiembro { get; set; }

        [Display(Name = "Comisión por sesión")]
        public virtual ComisionXSesion ComisionXSesion { get; set; }
        [Display(Name = "Usuario")]
        public virtual Usuario Usuario { get; set; }
    }
}
