
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Consilium.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Motion
{

    public int idMotion { get; set; }

    public string Tittle { get; set; }

    public Nullable<System.DateTime> Date { get; set; }

    public string member { get; set; }

    public string Proponentes { get; set; }

    public string Propuesta { get; set; }

}

}
