//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Consilium.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class ProponenteXMocion
    {
        [Display(Name = "ID Proponente")]
        public int idProponente { get; set; }
        [Display(Name = "ID Moción")]
        public int idMocion { get; set; }
        [Display(Name = "Identificación")]
        public string idUsuario { get; set; }
        [Display(Name = "Moción")]

        public virtual Mocion Mocion { get; set; }
        [Display(Name = "Usuario")]
        public virtual Usuario Usuario { get; set; }
    }
}
