//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;
namespace Consilium.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PuntoXAgenda
    {
        [Display(Name = "ID Puntos por agenda")]
        public int idPuntoXAgenda { get; set; }
        [Display(Name = "ID Agenda")]
        public Nullable<int> idAgenda { get; set; }
        [Display(Name = "ID Punto")]
        public Nullable<int> idPunto { get; set; }
        [Display(Name = "Agenda")]
        public virtual Agenda Agenda { get; set; }
        [Display(Name = "Punto")]
        public virtual Punto Punto { get; set; }
    }
}
