
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
namespace Consilium.Models
{

using System;
    using System.Collections.Generic;
    
public partial class PuntoXAgenda
{
        [Display(Name = "ID Punto Por Agenda")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "ID requerido")]
        public int idPuntoXAgenda { get; set; }
        [Display(Name = "ID Agenda")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "ID requerido")]
        public Nullable<int> idAgenda { get; set; }
        [Display(Name = "ID Punto")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "ID requerido")]
        public Nullable<int> idPunto { get; set; }

        [Display(Name = "ID Agenda")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "ID requerido")]

        public virtual Agenda Agenda { get; set; }
        [Display(Name = "Punto")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Punto requerido")]
        public virtual Punto Punto { get; set; }

}

}
