
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Consilium.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Request
{

    public int Id { get; set; }

    public Nullable<System.DateTime> Date { get; set; }

    public string Name { get; set; }

    public string MemberName { get; set; }

    public string MemberId { get; set; }

    public string Considerations { get; set; }

    public string Results { get; set; }

    public string Agreements { get; set; }

}

}
