
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Consilium.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Sesion
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Sesion()
    {

        this.MiembroXSesion = new HashSet<MiembroXSesion>();

        this.PuntoXSesion = new HashSet<PuntoXSesion>();

        this.ResultadoPunto = new HashSet<ResultadoPunto>();

        this.Comision = new HashSet<Comision>();

    }


    public string idSesion { get; set; }

    public int idTipo { get; set; }

    public System.DateTime fecha { get; set; }

    public Nullable<int> estado { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<MiembroXSesion> MiembroXSesion { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<PuntoXSesion> PuntoXSesion { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ResultadoPunto> ResultadoPunto { get; set; }

    public virtual TipoSesion TipoSesion { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Comision> Comision { get; set; }

}

}
