
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Consilium.Models
{

    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Usuario
    {

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuario()
        {

            this.Justificacion = new HashSet<Justificacion>();

            this.MiembroXComision = new HashSet<MiembroXComision>();

            this.ProponenteXMocion = new HashSet<ProponenteXMocion>();

            this.Punto = new HashSet<Punto>();

            this.MiembroXSesion = new HashSet<MiembroXSesion>();

        }


        [Display(Name = "Identificación")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Identificación vara requerida")]
        public string idUsuario { get; set; }

        [Display(Name = "Nombre")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Nombre requerido")]
        public string nombre { get; set; }

        [Display(Name = "Apellido Paterno")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Apellido parterno requerido")]
        public string apellidoP { get; set; }

        [Display(Name = "Apellido Materno")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Apellido marterno requerido")]
        public string apellidoM { get; set; }

        [Display(Name = "Tipo")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Tipo requerido")]
        public Nullable<int> tipo { get; set; }

        [Display(Name = "Estado")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Estado requerido")]
        public string estado { get; set; }

        [Display(Name = "Correo")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Correo requerido")]
        public string correo { get; set; }

        [Display(Name = "Teléfono")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Teléfono requerido")]
        public string telefono { get; set; }

        [Display(Name = "Fecha de inicio")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Fecha requerida")]
        public Nullable<System.DateTime> fechaInicio { get; set; }

        [Display(Name = "Fecha de fin")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Fecha requerida")]
        public Nullable<System.DateTime> fechaFin { get; set; }



        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

        public virtual ICollection<Justificacion> Justificacion { get; set; }

        public virtual Logueo Logueo { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

        public virtual ICollection<MiembroXComision> MiembroXComision { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

        public virtual ICollection<ProponenteXMocion> ProponenteXMocion { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

        public virtual ICollection<Punto> Punto { get; set; }

        public virtual TipoUsuario TipoUsuario { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

        public virtual ICollection<MiembroXSesion> MiembroXSesion { get; set; }

        public bool isSelected { get; set; }

    }
    public class UsuariosModelo
    {
        public List<Usuario> Usuarios { get; set; }

        public int? sesion { get; set; }
    }

}
